{% set name = "vyper-config" %}
{% set version = "1.1.1" %}

package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

source:
  url: "https://github.com/alexferl/vyper/archive/refs/tags/v{{ version }}.tar.gz"
  sha256: 6eab8a18987ac84e9c26395652b95f1ad6f03edbb7875a08cc53e6b4ed8ee235

build:
  number: 0
  skip: True  # [py<37]
  script: "{{ PYTHON }} -m pip install . -vv"

requirements:
  host:
    - pip
    - python
    - pytest-runner >=6.0.0
    - setuptools
    - wheel
  run:
    - distconfig3 >=1.0.1
    - python
    - pyyaml >=5.4.1
    - toml >=0.10.0
    - watchdog >=0.10.0

test:
  requires:
    - pip
  commands:
    - pip check
  imports:
    - vyper

about:
  home: https://github.com/alexferl/vyper
  license: MIT
  license_family: MIT
  license_file: LICENSE
  license_url: https://github.com/alexferl/vyper/blob/master/LICENSE
  summary: "Python configuration with (more) fangs"
  doc_url: https://github.com/alexferl/vyper
  dev_url: https://github.com/alexferl/vyper

extra:
  recipe-maintainers:
    - marcoesters
