{% set name = "vyper-config" %}
{% set version = "1.2.1" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: https://github.com/alexferl/vyper/archive/refs/tags/v{{ version }}.tar.gz
  sha256: 97ecbdf87a43ebf05b9e7c7fbf6e39da0852567e9c85f34f2918fd3ef70a4304

build:
  number: 0
  skip: True  # [py<38]
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  host:
    - pip
    - python
    - pytest-runner >=6.0.0
    - setuptools
    - wheel
  run:
    - distconfig3 >=1.0.1
    - python
    - pyyaml >=6.0.1
    - toml >=0.10.0
    - watchdog >=3.0.0

test:
  source_files:
    - tests
  imports:
    - vyper
  commands:
    - pip check
    - pytest -v tests
  requires:
    - pip
    - pytest

about:
  home: https://github.com/alexferl/vyper
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Python configuration with (more) fangs
  description: |
    Vyper is a complete configuration solution for Python applications including 12 factor apps.
    It is designed to work within an application, and can handle all types of configuration needs and formats.
  doc_url: https://github.com/alexferl/vyper/blob/v{{ version }}/README.md
  dev_url: https://github.com/alexferl/vyper

extra:
  recipe-maintainers:
    - marcoesters
